// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate with your actual Firebase project keys.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyDisciplineTrackerWeb001',
    appId: '1:1234567890:web:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'discipline-tracker-prod',
    authDomain: 'discipline-tracker-prod.firebaseapp.com',
    storageBucket: 'discipline-tracker-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyDisciplineTrackerAndroid001',
    appId: '1:1234567890:android:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'discipline-tracker-prod',
    storageBucket: 'discipline-tracker-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyDisciplineTrackerIOS001',
    appId: '1:1234567890:ios:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'discipline-tracker-prod',
    storageBucket: 'discipline-tracker-prod.appspot.com',
    iosBundleId: 'com.disciplinetracker.app',
  );
}
